#!/bin/sh

#################
# PRE-PROCESSES #
#################

mkdir -p $HOME/.cache/hentidl $HOME/.cache/hentidl/downloads
cachedir=$HOME/.cache/hentidl
ddir=$cachedir/downloads
version="0.2-beta"

#############
# FUNCTIONS #
#############

search () {
	query=$1
	curl -s "https://nhentai.net/search/?q=$query" > $cachedir/tmp.html
	url="https://nhentai.net$(cat $cachedir/tmp.html | grep -Eo "/g/[0-9]*/" | fzf)"
	curl -s $url > $cachedir/file.html
	downloader
}


downloader () {
	lasturl=$(cat $cachedir/file.html | grep -Eo "/g/[0-9]*/[0-9]*/" | tail -n 1)
	
	if [ -z $lasturl ]; then
		exit 1
	fi

	lp=$(echo $lasturl | cut -d'/' -f 4)
	base_code=$(cat $cachedir/file.html | grep -Eo "galleries/[0-9]*/"| cut -d'/' -f 2 | head -n 1)
	i=1

	while [ $i -lt $lp ]
	do
		echo "https://i5.nhentai.net/galleries/$base_code/$i.jpg" >> $cachedir/files.txt
		i=`expr $i + 1`
	done

	if [ -z $cachedir/files.txt ]; then
		exit 1
	fi

	aria2c --input-file $cachedir/files.txt -d $ddir
	rm $cachedir/files.txt
}

ssr () {
	seq=$1
	cd $ddir/
	chmod 766 $ddir/ssr
	$ddir/ssr $seq
	rm ssr
}


tag_search () {
	tag=$(cat assests/tags.txt | fzf)
	if [ -z $tag ]; then
		echo "[-] Tag is blank!"
		exit 1
	fi
	
	curl -s "https://nhentai.net/tag/$tag/" > $cachedir/tmp.html
	url="https://nhentai.net$(cat $cachedir/tmp.html | grep -Eo "/g/[0-9]*/" | fzf)"
	curl -s $url > $cachedir/file.html 
	downloader
}

rm_cache () {
	rm -rf $cachedir
}


help_text () {
	echo "\e[1;31m[+]\e[0m hentidl-$version"
	echo "\n\e[1;34mhelp-text: \e[1;36m"
	echo "\t./hentidl -t            [ tag_search      ]"
	echo "\t./hentidl -d <code>     [ download        ]"
	echo "\t./hentidl -s <query>    [ search          ]"
	echo "\t./hentidl -r            [ remove_cachedir ]"
	echo "\t./hentidl -h            [ help_text       ]"
	echo "\t./hentidl --version     [ hentidl_version ]"
	echo "\e[0m"
}

################
# MAIN PROGRAM #
################

if [ -z $1 ] || [ $1 = "-h" ]; then
	help_text
	exit 0
else
	if [ $1 = "-t" ]; then
		tag_search
	elif [ $1 = "-d" ]; then
		if [ -z $2 ]; then
			read -p "Enter Code: " code
		else
			code=$2
		fi
		curl -s "https://nhentai.net/g/$code/" > $cachedir/file.html
		downloader
	elif [ $1 = "-s" ]; then
		if [ -z $2 ]; then
			read -p "Search: "  query
		else
			query=$2
		fi
		search $query
	elif [ $1 = "-r" ]; then
		rm_cache
		exit 0
	elif [ $1 = "--version" ]; then
		echo "hentidl by hackerW1"
		echo "\tVersion: hentidl-$version"
		exit 0
	elif [ $1 = "-ssr" ]; then
		ssr
		exit 0
	else
		echo "\e[1;31m[-]\e[0m Syntax Error: "
		echo "\ttry: ./hentidl -h"
		exit 1
	fi
fi

# EOF
