#!/bin/sh

###########################
# simple sequence renamer #
###########################

version="0.2-beta"

if [ $1 = "-v" ] || [ $1 = "--version" ]; then
	echo "Simple-Sequence-Renamer: ssr-$version by hackerW1"
	exit 0
elif [ -z $1 ] || [ -z $2 ]; then
	echo "[-] Syntax Error"
	exit 1
fi

i=$1
l=`expr $2 + 1`

while [ $i -lt $l ]
do
	if [ $i -lt 10 ]; then
		mv $i.jpg 00$i.jpg
		i=`expr $i + 1`
	elif [ $i -lt 100 ]; then
		mv $i.jpg 0$i.jpg
		i=`expr $i + 1`
	elif [ $i -lt 1000 ]; then
		exit 0
	else
		echo "[-] Syntax Error"
		exit 1
	fi
done
