#!/bin/sh

###########################
# simple sequence renamer #
###########################

version=0.1

if [ -z $1 ]; then
	echo "[-] Syntax Error"
	exit
fi

firsts=1
middles=10
lasts=`expr $1 + 1`

if [ $1 -lt 10 ]; then
	while [ $firsts -lt $lasts ]
	do
		mv $firsts.jpg 0$firsts.jpg
		firsts=`expr $firsts + 1`
	done
elif [ $1 -gt 10 ] && [ $1 -lt 100 ]; then
	while [ $firsts -lt 10 ]
	do
		mv $firsts.jpg 00$firsts.jpg
		firsts=`expr $firsts + 1`
	done
	while [ $middles -lt $lasts ]
	do
		mv $middles.jpg 0$middles.jpg
		middles=`expr $middles + 1`
	done
else
	echo "[-] ssr-$version doesn't support numbers more than 100"
	exit
fi
